"""add google oauth fields

Revision ID: 8b91b0442ec5
Revises: 16e69eae899e
Create Date: 2026-06-15 17:52:16.074839

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "8b91b0442ec5"
down_revision: Union[str, Sequence[str], None] = "16e69eae899e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "auth_provider",
            sa.String(),
            nullable=False,
            server_default="local",
        ),
    )
    op.add_column("users", sa.Column("provider_user_id", sa.String(), nullable=True))
    op.alter_column(
        "users", "hashed_password", existing_type=sa.VARCHAR(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users", "hashed_password", existing_type=sa.VARCHAR(), nullable=False
    )
    op.drop_column("users", "provider_user_id")
    op.drop_column("users", "auth_provider")
    # ### end Alembic commands ###
