"""add cascade delete to transcriptions

Revision ID: 963645e74754
Revises: e8adec33ca77
Create Date: 2026-04-11 14:36:51.363767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '963645e74754'
down_revision: Union[str, Sequence[str], None] = 'e8adec33ca77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('audio_files_user_id_fkey'), 'audio_files', type_='foreignkey')
    op.create_foreign_key(None, 'audio_files', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('transcriptions_audio_file_id_fkey'), 'transcriptions', type_='foreignkey')
    op.create_foreign_key(None, 'transcriptions', 'audio_files', ['audio_file_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transcriptions', type_='foreignkey')
    op.create_foreign_key(op.f('transcriptions_audio_file_id_fkey'), 'transcriptions', 'audio_files', ['audio_file_id'], ['id'])
    op.drop_constraint(None, 'audio_files', type_='foreignkey')
    op.create_foreign_key(op.f('audio_files_user_id_fkey'), 'audio_files', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
