"""add google oauth fields

Revision ID: e3a1541f4438
Revises: 8b91b0442ec5
Create Date: 2026-06-15 18:11:35.506308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3a1541f4438'
down_revision: Union[str, Sequence[str], None] = '8b91b0442ec5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('provider_user_id', sa.String(), nullable=True))
    op.drop_column('users', 'provide_user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('provide_user_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('users', 'provider_user_id')
    # ### end Alembic commands ###
